2021-04-10 14:53:44,182 ERROR: Exception on /user/Andrei [GET] [in /Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/sqlalchemy/orm/base.py", line 406, in _entity_descriptor
    return getattr(entity, key)
AttributeError: type object 'Job' has no attribute 'user'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/inwaves/inwaves-repository/o.microtasks/app/main/routes.py", line 79, in user
    return render_template('user.html', user=user, tasks=tasks.items,
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/inwaves/inwaves-repository/o.microtasks/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/inwaves/inwaves-repository/o.microtasks/app/templates/base.html", line 8, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/inwaves/inwaves-repository/o.microtasks/app/templates/base.html", line 170, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/inwaves/inwaves-repository/o.microtasks/app/templates/user.html", line 31, in block "app_content"
    {% if not current_user.get_job_in_progress('export_tasks') %}
  File "/Users/inwaves/inwaves-repository/o.microtasks/app/models.py", line 201, in get_job_in_progress
    return Job.query.filter_by(user=self, name=name, complete=False).first()
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 1921, in filter_by
    clauses = [
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 1922, in <listcomp>
    _entity_descriptor(zero, key) == value
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/sqlalchemy/orm/base.py", line 408, in _entity_descriptor
    util.raise_(
  File "/Users/inwaves/anaconda3/envs/todo-backend/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: Entity '<class 'app.models.Job'>' has no property 'user'
2021-04-10 14:57:54,086 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 14:58:04,665 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 14:59:09,649 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 14:59:15,725 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
2021-04-10 14:59:22,293 INFO: Microblog startup [in /Users/inwaves/inwaves-repository/o.microtasks/app/__init__.py:92]
